# Generated by Django 5.0.1 on 2024-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Push Cart', 'Push Cart'), ('Food Truck', 'Food Truck')], max_length=255)),
                ('locationx', models.DecimalField(decimal_places=10, max_digits=15)),
                ('locationy', models.DecimalField(decimal_places=10, max_digits=15)),
                ('status', models.CharField(choices=[('accepted', 'ACCEPTED'), ('requested', 'REQUESTED')], max_length=255)),
                ('rel_distance', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=15, null=True)),
            ],
        ),
    ]
