# Generated by Django 5.0.1 on 2024-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='truckmodel',
            index=models.Index(fields=['rel_distance'], name='Truck_truck_rel_dis_365beb_idx'),
        ),
    ]
