# Generated by Django 5.0.1 on 2024-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0002_truckmodel_truck_truck_rel_dis_365beb_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
