# Generated by Django 5.0.1 on 2024-02-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0004_remove_truckmodel_truck_truck_rel_dis_365beb_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='truckmodel',
            index=models.Index(fields=['rel_distance'], name='Truck_truck_rel_dis_365beb_idx'),
        ),
    ]
